name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.7.3"

      - name: Install pnpm
        run: pnpm i

      - name: Build app
        run: pnpm build

      - name: Start app with PM2 on port 3049        
        run: pm2 reload fit-expert-front-prod-Runner
